import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { registerLicense } from '@syncfusion/ej2-base';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const licenseKey = process.env.NEXT_PUBLIC_SYNCFUSION_LICENSE || '';
registerLicense(licenseKey);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
